### PR TITLE
Treat network failure as cache miss

### LINKED ISSUE #23: AsyncAws errors are not caught
We have been getting a fair number of the following errors:

```
Unhandled AsyncAws\Core\Exception\Http\NetworkException (0) error: Could not contact remote server.
```

It seems like these `NetworkException` errors should be caught inside of `getRawItem` and throw a `CacheItemNotFoundException`, as in:

```php
try {
    return $item->getItem();
} catch (NetworkException) {
    throw new CacheItemNotFoundException();
}
```

### PR DESCRIPTION
**Pull request by shadowhand**
Fixes #23

### CODE REVIEW

**Comment by shadowhand** [comment]
@RikudouSage here's the fix for #23. This would really help us out, as it is not convenient (or possible) to wrap all cache usage in our application.

**Comment by RikudouSage** [comment]
I don't like it as a global behavior, I'd accept it if it was configurable and the default was to throw, but like this it's very misleading. I'm gonna take a look at the issue during the weekend.

**Comment by shadowhand** [comment]
@RikudouSage from my standpoint, failure to connect to DynamoDb killing a request is a huge problem, considering that there is nothing that can be done in user land to recover from that situation. A cache implementation needs to be as robust as possible and handle networking issues gracefully, because a cache layer should never be a point of failure.

**Comment by RikudouSage** [comment]
I've thought about it and I decided it makes more sense to have the default as a warning so it at least gets logged, does that make sense to you?

**Pull request merged**
